# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up', models.IntegerField(blank=True, null=True)),
                ('down', models.IntegerField(blank=True, null=True)),
                ('accepted', models.IntegerField(blank=True, null=True)),
                ('unaccepted', models.IntegerField(blank=True, null=True)),
                ('rejected', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
